# shared/unit.mk — included by every unit-level Makefile.
# Auto-detects PROJECT_ROOT and UNIT from CURDIR.
#
# A unit aggregates only the two products that concatenate meaningfully:
#
#   unitXX_student.pdf   unit cover + every lesson's student packet (+ sample test)
#   unitXX_key.pdf       the same, keyed, page for page with the student one
#
# The other two lesson products (the plan and the deck) stay per-lesson in
# target/compiled/unitXX/ — they are teacher artifacts, not something to hand
# out as one bound document. That is why unitXX_full.tex is gone.
#
# Pagination: each lesson packet arrives already numbered 1..n and already
# recto-correct, so the unit pass re-runs shared/paginate.sh over the merged
# unit packet. The white band in paginate.tex covers whatever number is already
# on the page and reprints it unit-wide, so the pass is idempotent and the two
# numbering schemes never fight. This replaced the unitXX_student.tex /
# unitXX_full.tex docmute wrappers, which achieved continuous numbering for the
# one unit that had them at the cost of a hand-maintained file per unit.

PROJECT_ROOT := $(abspath ..)
UNIT         := $(notdir $(CURDIR))
COMPILED_DIR := $(PROJECT_ROOT)/target/compiled
SHARED_STYS  := $(wildcard $(PROJECT_ROOT)/shared/*.sty)
TEXINPUTS    := $(PROJECT_ROOT)/shared//:
LATEXMK      = latexmk
LATEXFLAGS   = -xelatex \
               -interaction=nonstopmode \
               -halt-on-error \
               -file-line-error

PAGINATE_SH  := $(PROJECT_ROOT)/shared/paginate.sh
PAGINATE_DIR := $(PROJECT_ROOT)/target/$(UNIT)/.paginate

# Auto-discover lessons that have a Makefile, in sorted order.
LESSONS := $(patsubst %/Makefile,%,$(sort $(wildcard lesson*/Makefile)))

# Optional unit-level bookend components.
#
# binder_cover/ is a prefab-PDF component like sample_test/, with one
# difference: its main.pdf is generated by shared/cover.py rather than dropped
# in by hand. A unit opts in by having the directory at all. Its two identical
# pages are the front and back of the student's binder, so it leads the packet,
# ahead of the unit overview sheet.
HAS_BINDER_COVER    := $(wildcard binder_cover)
HAS_UNIT_COVER      := $(wildcard unit_cover/main.tex)
HAS_SAMPLE_TEST     := $(wildcard sample_test/main.pdf)
HAS_SAMPLE_TEST_KEY := $(wildcard sample_test_key/main.pdf)

BINDER_COVER_SRC    := $(if $(HAS_BINDER_COVER),binder_cover/main.pdf)
BINDER_COVER_PDF    := $(if $(HAS_BINDER_COVER),$(COMPILED_DIR)/$(UNIT)/binder_cover.pdf)
UNIT_COVER_PDF      := $(if $(HAS_UNIT_COVER),$(COMPILED_DIR)/$(UNIT)/unit_cover.pdf)
SAMPLE_TEST_PDF     := $(if $(HAS_SAMPLE_TEST),$(COMPILED_DIR)/$(UNIT)/sample_test.pdf)
SAMPLE_TEST_KEY_PDF := $(if $(HAS_SAMPLE_TEST_KEY),$(COMPILED_DIR)/$(UNIT)/sample_test_key.pdf)

PYTHON       ?= python3
COVER_SCRIPT := $(PROJECT_ROOT)/shared/cover.py

# The bookends the two packets pair off against each other. The cover is the
# same sheet in both. The sample test pairs with its key, or with itself when
# there is no key — either way the lists stay 1:1, which is what the alignment
# pass needs. (A sample_test_key with no sample_test is a malformed unit: the
# key packet would then carry one tail entry the student packet has not got.
# It sits at the very end, so everything ahead of it still aligns.)
STUDENT_TAIL := $(SAMPLE_TEST_PDF)
KEY_TAIL     := $(or $(SAMPLE_TEST_KEY_PDF),$(SAMPLE_TEST_PDF))

.PHONY: all student key full clean clean_unit_cover $(LESSONS) \
        binder_cover _binder_cover _unit_cover _sample_test _sample_test_key

all: _binder_cover $(LESSONS)

$(LESSONS):
	$(MAKE) -C $@

# ── Optional bookend rules ────────────────────────────────────────────────────

# The generated prefab. Declared .PHONY above so the binder_cover/ directory
# never shadows the convenience target of the same name.
#
# The rule has NO prerequisites on purpose: once generated, the cover is a
# committed artifact and stays put. Editing a lesson must not silently redraw
# the binder cover, and a regenerated cover is byte-different every time
# (cairosvg stamps a creation date) even when the art is identical, so
# dependency-tracking it would churn the repo for nothing. make creates it only
# when it is absent. To refresh it against the unit's current content:
#
#     make -C unitXX clean_unit_cover
ifdef HAS_BINDER_COVER
binder_cover: $(BINDER_COVER_SRC)

$(BINDER_COVER_SRC):
	$(PYTHON) $(COVER_SCRIPT) $(CURDIR)
endif

# Throw the current cover away and draw a new one from the unit as it stands.
clean_unit_cover:
ifdef HAS_BINDER_COVER
	rm -f $(BINDER_COVER_SRC) $(BINDER_COVER_PDF)
	@$(MAKE) --no-print-directory $(BINDER_COVER_SRC)
else
	@echo "  (no binder_cover/ in $(UNIT) — nothing to regenerate)"
endif

_binder_cover: $(BINDER_COVER_SRC)
ifdef HAS_BINDER_COVER
	@mkdir -p $(COMPILED_DIR)/$(UNIT)
	@cp $(BINDER_COVER_SRC) $(BINDER_COVER_PDF)
	@echo "✓  Binder cover      → target/compiled/$(UNIT)/binder_cover.pdf"
endif

_unit_cover:
ifdef HAS_UNIT_COVER
	@mkdir -p $(COMPILED_DIR)/$(UNIT)
	cd unit_cover && TEXINPUTS="$(PROJECT_ROOT)/shared//:" \
	    latexmk -xelatex -interaction=nonstopmode -halt-on-error -file-line-error \
	    -outdir="$(PROJECT_ROOT)/target/$(UNIT)/unit_cover" main.tex
	cp $(PROJECT_ROOT)/target/$(UNIT)/unit_cover/main.pdf $(UNIT_COVER_PDF)
	@echo "✓  Unit cover        → target/compiled/$(UNIT)/unit_cover.pdf"
endif

_sample_test:
ifdef HAS_SAMPLE_TEST
	@mkdir -p $(COMPILED_DIR)/$(UNIT)
	cp sample_test/main.pdf $(SAMPLE_TEST_PDF)
	@echo "✓  Sample test       → target/compiled/$(UNIT)/sample_test.pdf"
endif

_sample_test_key:
ifdef HAS_SAMPLE_TEST_KEY
	@mkdir -p $(COMPILED_DIR)/$(UNIT)
	cp sample_test_key/main.pdf $(SAMPLE_TEST_KEY_PDF)
	@echo "✓  Sample test key   → target/compiled/$(UNIT)/sample_test_key.pdf"
endif

# ── student / key packets ─────────────────────────────────────────────────────
#
# Both targets build BOTH packets of every lesson, because each one's slot sizes
# are computed against the other's. That is the price of page-for-page
# alignment, and it is why `make -C unitXX student` compiles the keys too.
#
# The paired lists are assembled from $(LESSONS) rather than by globbing, so
# they stay 1:1 and in the same order; a lesson missing either packet is
# skipped from both.
#
# Plain `=` rather than `define`: make collapses each backslash-newline in a
# variable assignment to one space, so this expands to a single shell line and
# can be dropped into either recipe.
unit_lesson_lists = sl=''; kl=''; \
  for l in $(LESSONS); do \
    s=$(COMPILED_DIR)/$(UNIT)/$$l"_student.pdf"; \
    k=$(COMPILED_DIR)/$(UNIT)/$$l"_key.pdf"; \
    if [ -f "$$s" ] && [ -f "$$k" ]; then sl="$$sl $$s"; kl="$$kl $$k"; fi; \
  done; \
  student_list="$(BINDER_COVER_PDF) $(UNIT_COVER_PDF) $$sl $(STUDENT_TAIL)"; \
  key_list="$(BINDER_COVER_PDF) $(UNIT_COVER_PDF) $$kl $(KEY_TAIL)"

student: _binder_cover _unit_cover _sample_test
	@for l in $(LESSONS); do $(MAKE) -C $$l student key || exit 1; done
	@mkdir -p $(COMPILED_DIR)/$(UNIT) $(COMPILED_DIR)
	@set -e; \
	$(unit_lesson_lists); \
	if [ -n "$$(echo $$student_list)" ]; then \
	  pdfunite $$student_list $(COMPILED_DIR)/$(UNIT)_student.pdf; \
	  TEXINPUTS="$(TEXINPUTS)" $(PAGINATE_SH) $(COMPILED_DIR)/$(UNIT)_student.pdf \
	      $(PAGINATE_DIR) $$student_list -- $$key_list; \
	  echo "✓  Unit student packet → target/compiled/$(UNIT)_student.pdf (paginated $(UNIT)-wide)"; \
	else \
	  echo "  (no student PDFs found for $(UNIT))"; \
	fi

key: _binder_cover _unit_cover _sample_test _sample_test_key
	@for l in $(LESSONS); do $(MAKE) -C $$l student key || exit 1; done
	@mkdir -p $(COMPILED_DIR)/$(UNIT) $(COMPILED_DIR)
	@set -e; \
	$(unit_lesson_lists); \
	if [ -n "$$(echo $$key_list)" ]; then \
	  pdfunite $$key_list $(COMPILED_DIR)/$(UNIT)_key.pdf; \
	  TEXINPUTS="$(TEXINPUTS)" $(PAGINATE_SH) $(COMPILED_DIR)/$(UNIT)_key.pdf \
	      $(PAGINATE_DIR) $$key_list -- $$student_list; \
	  echo "✓  Unit key packet     → target/compiled/$(UNIT)_key.pdf (page-for-page with the student packet)"; \
	else \
	  echo "  (no key PDFs found for $(UNIT))"; \
	fi

full:
	@echo "!  \`make full\` was removed — a unit now builds two packets:" >&2
	@echo "     make student  → $(UNIT)_student.pdf" >&2
	@echo "     make key      → $(UNIT)_key.pdf      (replaces \`full\`)" >&2
	@echo "   The lesson plans and decks it used to swallow are now standalone" >&2
	@echo "   per-lesson products: target/compiled/$(UNIT)/lessonYY_{plan,slides}.pdf" >&2
	@exit 1

clean:
	@for l in $(LESSONS); do $(MAKE) -C $$l clean; done
	rm -rf $(PROJECT_ROOT)/target/$(UNIT)/unit_cover $(PAGINATE_DIR)
	rm -f $(BINDER_COVER_PDF) $(UNIT_COVER_PDF) $(SAMPLE_TEST_PDF) $(SAMPLE_TEST_KEY_PDF)
	rm -f $(COMPILED_DIR)/$(UNIT)_student.pdf $(COMPILED_DIR)/$(UNIT)_key.pdf \
	      $(COMPILED_DIR)/$(UNIT)_full.pdf
